#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jq
Version  : 1.5
Release  : 5
URL      : https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz
Source0  : https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz
Summary  : Command-line JSON processor
Group    : Development/Tools
License  : MIT
Requires: jq-bin
Requires: jq-lib
Requires: jq-doc
BuildRequires : bison
BuildRequires : flex
BuildRequires : valgrind
Patch1: cve-2015-8863.patch
Patch2: cve-2016-4074.patch

%description
jq is a command-line JSON processor

%package bin
Summary: bin components for the jq package.
Group: Binaries

%description bin
bin components for the jq package.


%package dev
Summary: dev components for the jq package.
Group: Development
Requires: jq-lib
Requires: jq-bin
Provides: jq-devel

%description dev
dev components for the jq package.


%package doc
Summary: doc components for the jq package.
Group: Documentation

%description doc
doc components for the jq package.


%package lib
Summary: lib components for the jq package.
Group: Libraries

%description lib
lib components for the jq package.


%prep
%setup -q -n jq-1.5
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506006801
export CFLAGS="$CFLAGS -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fstack-protector-strong "
export FFLAGS="$CFLAGS -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1506006801
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jq

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libjq.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/jq/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjq.so.1
/usr/lib64/libjq.so.1.0.4
