#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jq
Version  : 1.6
Release  : 9
URL      : https://github.com/stedolan/jq/archive/jq-1.6.tar.gz
Source0  : https://github.com/stedolan/jq/archive/jq-1.6.tar.gz
Summary  : Command-line JSON processor
Group    : Development/Tools
License  : MIT
Requires: jq-bin = %{version}-%{release}
Requires: jq-lib = %{version}-%{release}
Requires: jq-license = %{version}-%{release}
Requires: jq-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : onig-dev
BuildRequires : valgrind

%description
jq is a command-line JSON processor

%package bin
Summary: bin components for the jq package.
Group: Binaries
Requires: jq-license = %{version}-%{release}

%description bin
bin components for the jq package.


%package dev
Summary: dev components for the jq package.
Group: Development
Requires: jq-lib = %{version}-%{release}
Requires: jq-bin = %{version}-%{release}
Provides: jq-devel = %{version}-%{release}
Requires: jq = %{version}-%{release}

%description dev
dev components for the jq package.


%package doc
Summary: doc components for the jq package.
Group: Documentation
Requires: jq-man = %{version}-%{release}

%description doc
doc components for the jq package.


%package lib
Summary: lib components for the jq package.
Group: Libraries
Requires: jq-license = %{version}-%{release}

%description lib
lib components for the jq package.


%package license
Summary: license components for the jq package.
Group: Default

%description license
license components for the jq package.


%package man
Summary: man components for the jq package.
Group: Default

%description man
man components for the jq package.


%prep
%setup -q -n jq-jq-1.6
cd %{_builddir}/jq-jq-1.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604542350
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1604542350
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jq
cp %{_builddir}/jq-jq-1.6/COPYING %{buildroot}/usr/share/package-licenses/jq/127289c8bb17ec76d9374c0d17ea2f85b79dd340
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jq

%files dev
%defattr(-,root,root,-)
/usr/include/jq.h
/usr/include/jv.h
/usr/lib64/libjq.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/jq/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjq.so.1
/usr/lib64/libjq.so.1.0.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jq/127289c8bb17ec76d9374c0d17ea2f85b79dd340

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/jq.1
